# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lr1A2C5TNYpN1GfUMbir573H0poEOaNB
"""

import numpy as np
from numpy import *



a= np. array([[2,3],
              [4,5]])
b= np.array([[6,7,],
             [8,9]])
print(np.vstack((a,b)))
print(np.hstack((a,b)))


print(np.column_stack((a,b)))
print(np.concatenate((a,b),1))

#creating a date and time
today=np.datetime64('2025-06-24')
print(today)
print(np.datetime64 ( today), 'y')
dates =np.arange('2025-06' , '2025-07' ,dtype='datetime64[D]')

print(dates)

print(today in dates)

dur = np.datetime64('2025-06-24') - np.datetime64('2024-06-24')
print(dur)

a = np.array(['2025-06-24', '2026-06-24','2027-06-24'], dtype= 'datetime64')
print(np.sort(a))