# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1juhvCxtcaeeRzLAjU1wnxwtZNrtoGuun
"""

import  seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

tips = pd.read_csv("/content/synthetic_health_lifestyle_dataset.csv")

tips.head()

sns.set(style = 'darkgrid',rc = {'figure.figsize':(10,6)},font_scale = 0.5)

sns.displot(tips["Height_cm"])

sns.displot

sns.displot(tips["Stress_Level"])

sns.displot(tips["Height_cm"], kde = True)

sns.distplot(tips['Height_cm'], hist = False, vertical= True, color = 'red')

sns.jointplot(x = 'Age', y = 'Stress_Level', data = tips)

sns.jointplot(x = 'Age', y = 'Height_cm', data = tips, kind = 'hex')